# Frontend CI workflow
# Cleans, builds, and deploys frontend app

name: Frontend CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: |
        touch .env.local
        echo "${{ secrets.DEV_ENV_FILE }}" > .env.local

    - run: npm run build --if-present

    # 🚀 Cleanup after build
    - name: Cleanup server
      if: always()
      run: |
        echo "🧹 Cleaning up frontend runner...."
        pkill -f "node" || true
        npm cache clean --force || true
        rm -rf ~/.npm/_cacache || true
        rm -rf ./node_modules || true   # safe to remove (npm ci reinstalls each run)
        rm -rf /tmp/* || true
        echo "✅ Frontend cleanup done"
